version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # default = monday
    open-pull-requests-limit: 30
    target-branch: "main"
    labels:
      - "dependencies"
      - "github"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 30
    labels:
      - "dependencies"
    ignore:
      # Major Angular updates should be done manually
      - dependency-name: "@angular/*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular-devkit/*"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 30
    labels:
      - "dependencies"
