/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {LiteralExpression} from "./literalExpression";


export interface Constraint {
    edctype: string;
    leftExpression: LiteralExpression;
    rightExpression: LiteralExpression;
    operator: string;
}

