/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Policy } from './policy';


export interface ContractAgreementDto {
    "edc:assetId": string;
    "edc:consumerId": string;
    "edc:contractSigningDate"?: number;
    "@id": string;
    "edc:policy": Policy;
    "edc:providerId": string;
    "@context": {[key:string] : string}
}

