/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Prohibition } from './prohibition';
import { Duty } from './duty';
import { Permission } from './permission';


export interface Policy {
    "@type": Policy.TypeEnum;
    "@id"?: string;
    assignee?: string;
    assigner?: string;
    inheritsFrom?: string;
    "odrl:obligation"?: Array<Duty>;
    "odrl:permission"?: Array<Permission>;
    "odrl:prohibition"?: Array<Prohibition>;
    "odrl:target"?: string;
}
export namespace Policy {
    export type TypeEnum = 'SET' | 'OFFER' | 'CONTRACT';
    export const TypeEnum = {
        Set: 'SET' as TypeEnum,
        Offer: 'OFFER' as TypeEnum,
        Contract: 'CONTRACT' as TypeEnum
    };
}


