version: "3.9"

services:
  consumer-data-dashboard:
    build: .
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "18080:80"
    volumes:
      - ./deployment/conf/consumer.nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/conf/consumer.config.json:/usr/share/nginx/html/assets/config/app.config.json

  provider-data-dashboard:
    build: .
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "28080:80"
    volumes:
      - ./deployment/conf/provider.nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/conf/provider.config.json:/usr/share/nginx/html/assets/config/app.config.json

  consumer-connector:
    build: deployment/connector
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "19191:9191" # connector default
      - "19192:9192" # connector control
      - "19193:9193" # connector management
      - "19194:9194" # connector protocol
      - "19291:9291" # data-plane public
    environment:
      EDC_VAULT: /config/vault.properties
      EDC_KEYSTORE: /config/vault-keys.p12
      EDC_KEYSTORE_PASSWORD: 123456
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./deployment/conf/consumer-connector.config:/config

  provider-connector:
    build: deployment/connector
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "29191:9191" # connector default
      - "29192:9192" # connector control
      - "29193:9193" # connector management
      - "29194:9194" # connector protocol
      - "29291:9291" # data-plane public
    environment:
      EDC_VAULT: /config/vault.properties
      EDC_KEYSTORE: /config/vault-keys.p12
      EDC_KEYSTORE_PASSWORD: 123456
      EDC_FS_CONFIG: /config/configuration.properties
    volumes:
      - ./deployment/conf/provider-connector.config:/config
