{{- if .Values.controlplane.oauth2Proxy.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "txdc.fullname" . }}-controlplane-oauth2-proxy
  labels:
    {{- include "txdc.controlplane.labels" . | nindent 4 }}
type: Opaque
data:
  OAUTH2_CLIENT_SECRET: {{ .Values.controlplane.oauth2Proxy.clientSecret | required ".Values.controlplane.endpoints.management.clientSecret is required" | b64enc | quote }}
  OAUTH2_COOKIE_SECRET: {{ .Values.controlplane.oauth2Proxy.cookieSecret | required ".Values.controlplane.endpoints.management.cookieSecret is required" | b64enc | quote }}
{{- end }}
