apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-pia-connector-ui.fullname" . }}-edc-config
  namespace: {{ .Release.Namespace | default "default" | quote }}
type: StringData
data:
  app.config.json: {{ tpl (.Files.Get "files/app.config.json") . | b64enc }}
    
