name: CD

on:
  push:
    branches:
      - 'main'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Build image'
        run: docker build -t data-dashboard .

      - name: 'Run container'
        run: docker run -p 8080:80 -d --rm --name data-dashboard data-dashboard

      - name: 'Verify container'
        run: |
          curl -O https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh -t 20 localhost:8080
