name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to GitHub Package Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
      - run: npm run lib-build
      - name: Publish
        run: npm publish
        working-directory: dist/dashboard-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
