name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to GitHub Package Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
      - run: npm run lib-build
      - name: Publish
        run: npm publish
        working-directory: dist/@eclipse-edc/dashboard-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
